//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditsView.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarNombreUsuario
        {
            get
            {
                return ((string)(this["GuardarNombreUsuario"]));
            }
            set
            {
                this["GuardarNombreUsuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCodigoUsuario
        {
            get
            {
                return ((string)(this["GuardarCodigoUsuario"]));
            }
            set
            {
                this["GuardarCodigoUsuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarNombrePerfil
        {
            get
            {
                return ((string)(this["GuardarNombrePerfil"]));
            }
            set
            {
                this["GuardarNombrePerfil"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarClaveUsuario
        {
            get
            {
                return ((string)(this["GuardarClaveUsuario"]));
            }
            set
            {
                this["GuardarClaveUsuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCheckUsuario
        {
            get
            {
                return ((string)(this["GuardarCheckUsuario"]));
            }
            set
            {
                this["GuardarCheckUsuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCheckClave
        {
            get
            {
                return ((string)(this["GuardarCheckClave"]));
            }
            set
            {
                this["GuardarCheckClave"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoIngresos
        {
            get
            {
                return ((string)(this["GuardarPeriodoIngresos"]));
            }
            set
            {
                this["GuardarPeriodoIngresos"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoSalidas
        {
            get
            {
                return ((string)(this["GuardarPeriodoSalidas"]));
            }
            set
            {
                this["GuardarPeriodoSalidas"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoTransferencias
        {
            get
            {
                return ((string)(this["GuardarPeriodoTransferencias"]));
            }
            set
            {
                this["GuardarPeriodoTransferencias"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoMovimientos
        {
            get
            {
                return ((string)(this["GuardarPeriodoMovimientos"]));
            }
            set
            {
                this["GuardarPeriodoMovimientos"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-VQ0I0E0\\SQLEXPRESS;Initial Catalog=DbFbpol;Persist" +
            " Security Info=True;User ID=sa;Password=.")]
        public string Almacen_ProduccionConnectionString
        {
            get
            {
                return ((string)(this["DbFbpolConnectionString"]));
            }
        }
    }
}
